version: '3'

services:
  pocpdvadminrabbitmq:
    build: .
    container_name: POC-PdvAdminRabbitMQ
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/home/node/app
    ports:
      - '9229:9229'
      - '${PORT}:${PORT}'
    networks:
      - pocpdvadminrabbitmq-net

  pocpdvadminrabbitmq-rabbit:
    image: "rabbitmq:3-management"
    hostname: pocpdvadminrabbitmq-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - pocpdvadminrabbitmq-net

networks:
  pocpdvadminrabbitmq-net:
    driver: bridge